# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b123ff6c3dbb0af549cfc3fde26c220d665ff4d6a89c08fcfa4caed12e1ccf8b6297c962dd977d3cb2101dce084e21c9574974afc26847dd4e7e35d28a2fa841
  twitter_api_key: M8rjAYXvHpoqkmQaTGx8SW5d7
  twitter_api_secret: 2TPQ2nwzS2QY7RXgyzsLx0oGuFbQjhFdc32wBh1OsqDDmrI1Ur
test:
  secret_key_base: 729b8a3837f331237b575803dd8180948da143fe58028097c12f0047e19ba271c5642399b9de72ab51758a03b50835eaa6179cfa6c3b78da3f553c9d3301d4af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
